server:
  port: 9091

spring:
  application:
    name: log-processor
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:db/eventsdb;DB_CLOSE_DELAY=1000
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

app:
  log-processor:
    alert-threshold-ms: 4
    table-rows-writeoff-count: 1000
